#!/usr/bin/python
# -*- coding: latin-1 -*-
import os, sys

def ayudaPrincipal():
	print " --------------------------------------------------------------------------------------"
	print "|                                                                                     |"
	print "| \tALGORITMOS CRIPTOGRAFICOS                                                     |"
	print "|										      |"
	print "| sintaxis: python principal.py <algoritmo>					      |"
	print "|										      |"
	print "| <algoritmo>:									      |"
	print "|\t-sc    Algoritmo de sustitución monoalfabética Julio Cesar		      |"
	print "|\t-sa    Algoritmo de sustitución monoalfabética afin			      |"
	print "|\t-sva   Algoritmo de sustitución polialfabética Vigenere Autoclave	      |"
	print "|										      |"
	print "| consultar ayuda de un algoritmo en específico: 				      |"
	print "|                                   sintaxis: python principal.py <algoritmo>	      |"
	print "|										      |"
	print "| Elaborado por:  Jonathan Ibarra						      |"
	print "|                 Tania Cañizares						      |"
	print "|         									      |"
	print " --------------------------------------------------------------------------------------"

def ayudaVigenere():
	print " --------------------------------------------------------------------------------------"
	print "|                                                                                     |"
	print "| \tALGORITMO VIGENERE AUTOCLAVE                                                  |"
	print "|										      |"
	print "|  ********************************************************************************** |"
	print "|  !!!ESTE ALGORITMO TRABAJA CON EL ALFABETO ASCII 128 Y LA Ñ SE TRATA COMO UNA N¡¡¡  |"
	print "|  ********************************************************************************** |"
	print "|										      |"
	print "| sintaxis: python principal.py -sva <modo> <archivoEntrada> <clave> <archivoSalida>  |"
	print "|										      |"
	print "| <modo>:									      |"
	print "|\t-c    para cifrar el archivo			             		      |"
	print "|\t-d    para decifrar el archivo                  			      |"
	print "| 										      |"
	print "| <archivoEntrada>: Nombre del archivo de entrada a cifrar o descifrar ej: quijote.txt|"
	print "|										      |"
	print "| <clave>: la clave con la que se cifrara o descifrara el archivo                     |"
	print "|										      |"
	print "| <archivoSalida>: Nombre del archivo de salida del algoritmo ej: quijote.txt         |"
	print "|										      |"
	print "| Ejemplos:    					 				      |"
	print "|\tcifrar: python principal.py -sva -c quijote.txt clave_VIGENERE quijote.cif    |"
	print "|\tdescifrar: python principal.py -sva -d quijote.cif clave_VIGENERE quijote.txt |"
	print "|										      |"
	print "| Elaborado por:  Jonathan Ibarra						      |"
	print "|         									      |"
	print " --------------------------------------------------------------------------------------"

def ayudaCesar():
	print " --------------------------------------------------------------------------------------"
	print "|                                                                                     |"
	print "| \tALGORITMO CESAR		                                                      |"
	print "|										      |"
	print "|  ********************************************************************************** |"
	print "|  !!!ESTE ALGORITMO TRABAJA CON EL ALFABETO EN INGLES Y LA Ñ SE TRATA COMO UNA N¡¡¡  |"
	print "|  ********************************************************************************** |"
	print "|										      |"
	print "| sintaxis: python principal.py -sc <modo> <archivoEntrada> <clave> <archivoSalida>   |"
	print "|										      |"
	print "| <modo>:									      |"
	print "|\t-c    para cifrar el archivo			             		      |"
	print "|\t-d    para decifrar el archivo                  			      |"
	print "| 										      |"
	print "| <archivoEntrada>: Nombre del archivo de entrada a cifrar o descifrar ej: quijote.txt|"
	print "|										      |"
	print "| <clave>: es un numero que corresponde al desplazamiento del alfabeto                |"
	print "|										      |"
	print "| <archivoSalida>: Nombre del archivo de salida del algoritmo ej: quijote.txt         |"
	print "|										      |"
	print "| Ejemplos:    					 				      |"
	print "|\tcifrar: python principal.py -sc -c quijote.txt 4 quijote.cif                  |"
	print "|\tdescifrar: python principal.py -sc -d quijote.cif 4 quijote.txt               |"
	print "|										      |"
	print "| Elaborado por:  Tania Cañizares						      |"
	print "|         									      |"
	print " --------------------------------------------------------------------------------------"

def ayudaAfin():
	print " --------------------------------------------------------------------------------------"
	print "|                                                                                     |"
	print "| \tALGORITMO AFIN		                                                      |"
	print "|										      |"
	print "|  ********************************************************************************** |"
	print "|  !!!ESTE ALGORITMO TRABAJA CON EL ALFABETO EN INGLES Y LA Ñ SE TRATA COMO UNA N¡¡¡  |"
	print "|  ********************************************************************************** |"
	print "|										      |"
	print "| sintaxis: python principal.py -sa <modo> <archivoEntrada> <a> <b> <archivoSalida>   |"
	print "|										      |"
	print "| <modo>:									      |"
	print "|\t-c    para cifrar el archivo			             		      |"
	print "|\t-d    para decifrar el archivo                  			      |"
	print "| 										      |"
	print "| <archivoEntrada>: Nombre del archivo de entrada a cifrar o descifrar ej: quijote.txt|"
	print "|										      |"
	print "| a y b deben estar en el siguiente rango 0<(a,b)<n-1  con n=26 		      |"
	print "|										      |"
	print "| <a>: es un numero que sea co-primo con n (mcd(a,n)=1)      n=26                     |"
	print "|										      |"
	print "| <b>: es un numero que corresponde al desplazamiento del alfabeto(clave)             |"
	print "|										      |"
	print "| <archivoSalida>: Nombre del archivo de salida del algoritmo ej: quijote.txt         |"
	print "|										      |"
	print "| Ejemplos:    					 				      |"
	print "|\tcifrar: python principal.py -sa -c quijote.txt 15 4 quijote.cif               |"
	print "|\tdescifrar: python principal.py -sa -d quijote.cif 15 4 quijote.txt            |"
	print "|										      |"
	print "| Elaborado por:  Tania Cañizares						      |"
	print "|         									      |"
	print " --------------------------------------------------------------------------------------"

